public class Calculator {
   
    public static void addititon(Integer a, Integer b){
        Integer add;
        add= a+b;
        System.debug('Sum'+add);
    }
    public static void subtraction(Integer a, Integer b){
        Integer sub;
        sub=a-b;
        System.debug('Sum'+sub);
    }
    public static void multiply(Integer a, Integer b){
        Integer mul;
      mul = a*b;
        System.debug('Sum'+mul);
    }
    public static void division(Integer a, Integer b){
        Integer div;
        div= a/b;
        System.debug('Sum'+div);
    }

}